### ISSUE TITLE
Error while importing Client

### ISSUE THREAD

**Issue by jonatasbaldin** [getyoti/yoti-python-sdk#17]
Hello there!

While importing the `Client` – as suggested by the documentation – I got the following error:

```
>>> from yoti_python_sdk import Client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jonatasbaldin/python_envs/morty/lib/python3.6/site-packages/yoti_python_sdk/__init__.py", line 4, in <module>
    from yoti_python_sdk.client import Client
  File "/Users/jonatasbaldin/python_envs/morty/lib/python3.6/site-packages/yoti_python_sdk/client.py", line 14, in <module>
    from config import SDK_IDENTIFIER
ModuleNotFoundError: No module named 'config'
```

I think the error is that the `config.py` file should be inside the package, not on the repository root. I opened #16, which fixes it.

Also, I'm running Python 3.6.

Also, on the [Yoti Developers Page](https://www.yoti.com/developers/documentation/?python#4-retrieving-a-profile) the documentation is different than this readme, specifying: `from yoti import Client`.

Thanks!

**Comment by echarrod** [comment]
Thanks Jonatas, the documentation will also be updated shortly to reflect the latest import.
Edward

**Comment by jonatasbaldin** [comment]
Yay! Thank you :)
